# .streamlit/config.toml
[theme]
primaryColor="#4FB477"
backgroundColor="#F4F4F9"
secondaryBackgroundColor="#556B77"
textColor="#070600"
font="sans serif"

[server] 
enableXsrfProtection = false
"folderWatch 黑名单" = ["/home/adminuser/venv/"] 

[runner] 
python_version = "3.10"